/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 TV3.glb 
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export default function TVScreen(props) {
  const { nodes, materials } = useGLTF("./Model/TV3.glb");
  const tvBackPanel = useTexture("./Textures/gpt1.jpg");
  const tvScreen = useTexture("./Textures/cement.jpg");

  const handleClick = (url) => {
    if (props.opacity > 0.9) {
      window.open(url, "_blank");
    }
  };
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[35, 30.69, 10]}
        rotation={[Math.PI / 2, 0, 1.5]}
        scale={[10, 1, 10]}
        onClick={() => {
          console.log("Bellow");
        }}
      >
        <meshBasicMaterial map={tvBackPanel} />
      </mesh>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[34.9, 30.69, 10]}
        scale={[19, 0, 10]}
        onClick={() => {
          console.log("hello");
        }}
        rotation={[Math.PI / 2, 0, 1.5]}
      >
        <meshBasicMaterial map={tvScreen} />
      </mesh>
    </group>
  );
}

useGLTF.preload("./Model/TV3.glb");
